wip: update to new solr cloud operator

diff --git a/manifests/solr-operator.yml b/manifests/solr-operator.yml
--- a/manifests/solr-operator.yml
+++ b/manifests/solr-operator.yml
@@ -7,9 +7,9 @@ metadata:
   namespace: solr-operator
   labels:
     app.kubernetes.io/name: zookeeper-operator
-    app.kubernetes.io/version: "0.2.9"
+    app.kubernetes.io/version: "0.2.15"
     app.kubernetes.io/managed-by: Helm
-    helm.sh/chart: "zookeeper-operator-0.2.9"
+    helm.sh/chart: "zookeeper-operator-0.2.15"
 ---
 # Source: solr-operator/templates/service_account.yaml
 # Licensed to the Apache Software Foundation (ASF) under one or more
@@ -30,18 +30,18 @@ apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: solr-operator
+  namespace: solr-operator
 ---
 # Source: solr-operator/charts/zookeeper-operator/templates/clusterrole.yaml
 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: solr-operator-zookeeper-operator
-  namespace: solr-operator
   labels:
     app.kubernetes.io/name: zookeeper-operator
-    app.kubernetes.io/version: "0.2.9"
+    app.kubernetes.io/version: "0.2.15"
     app.kubernetes.io/managed-by: Helm
-    helm.sh/chart: "zookeeper-operator-0.2.9"
+    helm.sh/chart: "zookeeper-operator-0.2.15"
 rules:
 - apiGroups:
   - zookeeper.pravega.io
@@ -52,6 +52,7 @@ rules:
 - apiGroups:
   - ""
   resources:
+  - nodes
   - pods
   - services
   - endpoints
@@ -104,8 +105,6 @@ rules:
   - configmaps/status
   verbs:
   - get
-  - patch
-  - update
 - apiGroups:
   - ""
   resources:
@@ -136,6 +135,7 @@ rules:
   - pods/status
   verbs:
   - get
+  - patch
 - apiGroups:
   - ""
   resources:
@@ -166,8 +166,6 @@ rules:
   - services/status
   verbs:
   - get
-  - patch
-  - update
 - apiGroups:
   - apps
   resources:
@@ -204,28 +202,6 @@ rules:
   - statefulsets/status
   verbs:
   - get
-  - patch
-  - update
-- apiGroups:
-  - batch
-  resources:
-  - jobs
-  verbs:
-  - create
-  - delete
-  - get
-  - list
-  - patch
-  - update
-  - watch
-- apiGroups:
-  - batch
-  resources:
-  - jobs/status
-  verbs:
-  - get
-  - patch
-  - update
 - apiGroups:
   - networking.k8s.io
   resources:
@@ -244,8 +220,18 @@ rules:
   - ingresses/status
   verbs:
   - get
+- apiGroups:
+  - policy
+  resources:
+  - poddisruptionbudgets
+  verbs:
+  - create
+  - delete
+  - get
+  - list
   - patch
   - update
+  - watch
 - apiGroups:
   - solr.apache.org
   resources:
@@ -258,6 +244,12 @@ rules:
   - patch
   - update
   - watch
+- apiGroups:
+  - solr.apache.org
+  resources:
+  - solrbackups/finalizers
+  verbs:
+  - update
 - apiGroups:
   - solr.apache.org
   resources:
@@ -307,6 +299,12 @@ rules:
 - apiGroups:
   - solr.apache.org
   resources:
+  - solrprometheusexporters/finalizers
+  verbs:
+  - update
+- apiGroups:
+  - solr.apache.org
+  resources:
   - solrprometheusexporters/status
   verbs:
   - get
@@ -330,20 +328,17 @@ rules:
   - zookeeperclusters/status
   verbs:
   - get
-  - patch
-  - update
 ---
 # Source: solr-operator/charts/zookeeper-operator/templates/clusterrolebinding.yaml
 kind: ClusterRoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: solr-operator-zookeeper-operator
-  namespace: solr-operator
   labels:
     app.kubernetes.io/name: zookeeper-operator
-    app.kubernetes.io/version: "0.2.9"
+    app.kubernetes.io/version: "0.2.15"
     app.kubernetes.io/managed-by: Helm
-    helm.sh/chart: "zookeeper-operator-0.2.9"
+    helm.sh/chart: "zookeeper-operator-0.2.15"
 subjects:
 - kind: ServiceAccount
   name: zookeeper-operator
@@ -376,9 +371,9 @@ metadata:
   namespace: solr-operator
   labels:
     app.kubernetes.io/name: zookeeper-operator
-    app.kubernetes.io/version: "0.2.9"
+    app.kubernetes.io/version: "0.2.15"
     app.kubernetes.io/managed-by: Helm
-    helm.sh/chart: "zookeeper-operator-0.2.9"
+    helm.sh/chart: "zookeeper-operator-0.2.15"
 rules:
 - apiGroups:
   - zookeeper.pravega.io
@@ -414,6 +409,46 @@ rules:
   verbs:
   - "*"
 ---
+# Source: solr-operator/templates/leader_election_role.yaml
+# permissions to do leader election.
+apiVersion: rbac.authorization.k8s.io/v1
+kind: Role
+metadata:
+  name: solr-operator-leader-election-role
+  namespace: solr-operator
+rules:
+- apiGroups:
+  - ""
+  resources:
+  - configmaps
+  verbs:
+  - get
+  - list
+  - watch
+  - create
+  - update
+  - patch
+  - delete
+- apiGroups:
+  - coordination.k8s.io
+  resources:
+  - leases
+  verbs:
+  - get
+  - list
+  - watch
+  - create
+  - update
+  - patch
+  - delete
+- apiGroups:
+  - ""
+  resources:
+  - events
+  verbs:
+  - create
+  - patch
+---
 # Source: solr-operator/charts/zookeeper-operator/templates/rolebinding.yaml
 kind: RoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
@@ -422,9 +457,9 @@ metadata:
   namespace: solr-operator
   labels:
     app.kubernetes.io/name: zookeeper-operator
-    app.kubernetes.io/version: "0.2.9"
+    app.kubernetes.io/version: "0.2.15"
     app.kubernetes.io/managed-by: Helm
-    helm.sh/chart: "zookeeper-operator-0.2.9"
+    helm.sh/chart: "zookeeper-operator-0.2.15"
 subjects:
 - kind: ServiceAccount
   name: zookeeper-operator
@@ -432,6 +467,21 @@ roleRef:
   kind: Role
   name: solr-operator-zookeeper-operator
   apiGroup: rbac.authorization.k8s.io
+---
+# Source: solr-operator/templates/leader_election_role_binding.yaml
+apiVersion: rbac.authorization.k8s.io/v1
+kind: RoleBinding
+metadata:
+  name: solr-operator-leader-election-rolebinding
+  namespace: solr-operator
+roleRef:
+  apiGroup: rbac.authorization.k8s.io
+  kind: Role
+  name: solr-operator-leader-election-role
+subjects:
+  - kind: ServiceAccount
+    name: solr-operator
+    namespace: solr-operator
 ---
 # Source: solr-operator/charts/zookeeper-operator/templates/operator.yaml
 apiVersion: apps/v1
@@ -441,9 +491,9 @@ metadata:
   namespace: solr-operator
   labels:
     app.kubernetes.io/name: zookeeper-operator
-    app.kubernetes.io/version: "0.2.9"
+    app.kubernetes.io/version: "0.2.15"
     app.kubernetes.io/managed-by: Helm
-    helm.sh/chart: "zookeeper-operator-0.2.9"
+    helm.sh/chart: "zookeeper-operator-0.2.15"
 spec:
   replicas: 1
   selector:
@@ -458,7 +508,7 @@ spec:
       serviceAccountName: zookeeper-operator
       containers:
       - name: solr-operator-zookeeper-operator
-        image: "pravega/zookeeper-operator:0.2.9"
+        image: "pravega/zookeeper-operator:0.2.15"
         imagePullPolicy: IfNotPresent
         ports:
         - containerPort: 6000
@@ -495,6 +545,7 @@ apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: solr-operator
+  namespace: solr-operator
   labels:
     control-plane: solr-operator
 spec:
@@ -512,12 +563,16 @@ spec:
       serviceAccountName: solr-operator
       containers:
       - name: solr-operator
-        image: "apache/solr-operator:v0.3.0" 
+        image: "apache/solr-operator:v0.7.0" 
         imagePullPolicy: IfNotPresent
         args:
-        # DEPRECATION: v0.4.0 - Remove (eq "true" .Values.useZkOperator)
         - -zk-operator=true
         - --tls-skip-verify-server=true
+        - --tls-watch-cert=true
+        - "--health-probe-bind-address=:8081"
+        - "--metrics-bind-address=:8080"
+        - "--leader-elect=true"
+
         env:
           - name: POD_NAMESPACE
             valueFrom:
@@ -527,9 +582,61 @@ spec:
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
+
+        securityContext:
+          allowPrivilegeEscalation: false
+          runAsNonRoot: true
+        livenessProbe:
+          httpGet:
+            path: /healthz
+            port: 8081
+          initialDelaySeconds: 15
+          periodSeconds: 20
+        readinessProbe:
+          httpGet:
+            path: /readyz
+            port: 8081
+          initialDelaySeconds: 5
+          periodSeconds: 10
+
         resources:
           {}
+        ports:
+          - containerPort: 8080
+            name: metrics
       terminationGracePeriodSeconds: 10
+---
+# Source: solr-operator/templates/leader_election_role.yaml
+# Licensed to the Apache Software Foundation (ASF) under one or more
+# contributor license agreements.  See the NOTICE file distributed with
+# this work for additional information regarding copyright ownership.
+# The ASF licenses this file to You under the Apache License, Version 2.0
+# (the "License"); you may not use this file except in compliance with
+# the License.  You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+---
+# Source: solr-operator/templates/leader_election_role_binding.yaml
+# Licensed to the Apache Software Foundation (ASF) under one or more
+# contributor license agreements.  See the NOTICE file distributed with
+# this work for additional information regarding copyright ownership.
+# The ASF licenses this file to You under the Apache License, Version 2.0
+# (the "License"); you may not use this file except in compliance with
+# the License.  You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 ---
 # Source: solr-operator/templates/role.yaml
 # Licensed to the Apache Software Foundation (ASF) under one or more
@@ -574,6 +681,17 @@ metadata:
     "helm.sh/hook-weight": "1"
     "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
 ---
+# Source: solr-operator/charts/zookeeper-operator/templates/pre-delete-hooks.yaml
+apiVersion: v1
+kind: ServiceAccount
+metadata:
+  name: solr-operator-zookeeper-operator-pre-delete
+  namespace: solr-operator
+  annotations:
+    "helm.sh/hook": pre-delete
+    "helm.sh/hook-weight": "1"
+    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
+---
 # Source: solr-operator/charts/zookeeper-operator/templates/post-install-upgrade-hooks.yaml
 apiVersion: v1
 kind: ConfigMap
@@ -593,6 +711,74 @@ data:
     if [ -z "$(kubectl api-resources | grep ZookeeperCluster)" ]; then
         exit 1
     fi
+---
+# Source: solr-operator/charts/zookeeper-operator/templates/pre-delete-hooks.yaml
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: solr-operator-zookeeper-operator-pre-delete
+  namespace: solr-operator
+  annotations:
+    "helm.sh/hook": pre-delete
+    "helm.sh/hook-weight": "1"
+    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
+data:
+  pre-delete.sh: |
+    #!/bin/sh
+    exit_code=0
+    echo "Checking for ZookeeperCluster Resource"
+
+    ret=$(kubectl get zookeepercluster --all-namespaces --no-headers 2>&1)
+    if (echo $ret | grep -e "No resources found" -e "the server doesn't have a resource type \"zookeepercluster\"" > /dev/null);
+    then
+      echo "None"
+    else
+      echo "$ret"
+      exit_code=1
+    fi
+
+    if [ $exit_code -ne 0 ];
+    then
+      echo "Pre-delete Check Failed"
+      exit $exit_code
+    fi
+    echo "Pre-delete Check OK"
+---
+# Source: solr-operator/charts/zookeeper-operator/templates/pre-delete-hooks.yaml
+kind: ClusterRole
+apiVersion: rbac.authorization.k8s.io/v1
+metadata:
+  name: solr-operator-zookeeper-operator-pre-delete
+  annotations:
+    "helm.sh/hook": pre-delete
+    "helm.sh/hook-weight": "1"
+    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
+rules:
+- apiGroups:
+  - zookeeper.pravega.io
+  resources:
+  - "*"
+  verbs:
+  - get
+  - list
+---
+# Source: solr-operator/charts/zookeeper-operator/templates/pre-delete-hooks.yaml
+kind: ClusterRoleBinding
+apiVersion: rbac.authorization.k8s.io/v1
+metadata:
+  name: solr-operator-zookeeper-operator-pre-delete
+  annotations:
+    "helm.sh/hook": pre-delete
+    "helm.sh/hook-weight": "1"
+    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
+subjects:
+  - kind: ServiceAccount
+    name: solr-operator-zookeeper-operator-pre-delete
+    namespace: solr-operator
+roleRef:
+  kind: ClusterRole
+  name: solr-operator-zookeeper-operator-pre-delete
+  apiGroup: rbac.authorization.k8s.io
 ---
 # Source: solr-operator/charts/zookeeper-operator/templates/post-install-upgrade-hooks.yaml
 kind: Role
@@ -657,7 +843,7 @@ spec:
       restartPolicy: Never
       containers:
       - name: post-install-upgrade-job
-        image: "lachlanevenson/k8s-kubectl:v1.16.10"
+        image: "lachlanevenson/k8s-kubectl:v1.23.2"
         command:
           - /scripts/validations.sh
         volumeMounts:
@@ -668,4 +854,37 @@ spec:
         - name: sh
           configMap:
             name: solr-operator-zookeeper-operator-post-install-upgrade
+            defaultMode: 0555
+---
+# Source: solr-operator/charts/zookeeper-operator/templates/pre-delete-hooks.yaml
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: solr-operator-zookeeper-operator-pre-delete
+  namespace: solr-operator
+  annotations:
+    "helm.sh/hook": pre-delete
+    "helm.sh/hook-weight": "2"
+    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
+spec:
+  backoffLimit: 6
+  template:
+    metadata:
+      name: solr-operator-zookeeper-operator-pre-delete
+    spec:
+      serviceAccountName: solr-operator-zookeeper-operator-pre-delete
+      restartPolicy: Never
+      containers:
+        - name: pre-delete-job
+          image: "lachlanevenson/k8s-kubectl:v1.23.2"
+          command:
+            - /scripts/pre-delete.sh
+          volumeMounts:
+            - name: sh
+              mountPath: /scripts
+              readOnly: true
+      volumes:
+        - name: sh
+          configMap:
+            name: solr-operator-zookeeper-operator-pre-delete
             defaultMode: 0555
